server:
  port: 9191

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    template:
      default-topic: my-default-topic

app:
  kafka:
    topic:
      partitioned: partitioned-kafka-topic
      non-partitioned: non-partitioned-kafka-topic
      partition-count: 4
      replication-factor: 1